function getDismissDialogScript() {
  return "(() => {\n    const texts = ['我知道了', '知道了', '关闭', '暂不', '以后再说', '取消'];\n    const nodes = Array.from(document.querySelectorAll('button, [role=\"button\"], .semi-button, span, div'));\n    for (const el of nodes) {\n      const t = (el.innerText || el.textContent || '').trim();\n      if (!t || t.length > 12) continue;\n      if (texts.some((x) => t === x || t.includes(x))) {\n        try { el.click(); return { ok: true, text: t }; } catch (_) {}\n      }\n    }\n    return { ok: false };\n  })()";
}
function getPageProbeScript() {
  return "(() => {\n    const bodyText = (document.body && (document.body.innerText || '')) || '';\n    const hasLogin = /扫码登录|手机号登录|登录后即可|请登录/.test(bodyText);\n    const fileInputs = Array.from(document.querySelectorAll('input[type=\"file\"]')).map((el, i) => ({\n      index: i,\n      accept: el.getAttribute('accept') || '',\n      multiple: !!el.multiple,\n      visible: !!(el.offsetParent || el.getClientRects().length),\n    }));\n    const titleHints = Array.from(document.querySelectorAll('input, textarea, [contenteditable=\"true\"]'))\n      .slice(0, 20)\n      .map((el) => ({\n        tag: el.tagName,\n        placeholder: el.getAttribute('placeholder') || '',\n        aria: el.getAttribute('aria-label') || '',\n        contenteditable: el.getAttribute('contenteditable') || '',\n      }));\n    const publishBtns = Array.from(document.querySelectorAll('button, [role=\"button\"]'))\n      .map((el) => (el.innerText || el.textContent || '').trim())\n      .filter((t) => t && t.length <= 10 && /发布|定时发布|存草稿/.test(t))\n      .slice(0, 10);\n    const progress = /文件解析中|上传中|(\\d+\\s*%)/.test(bodyText);\n    const editReady = /作品描述|添加作品描述|输入作品标题|填写作品标题|标题/.test(bodyText)\n      && (fileInputs.length === 0 || !progress || /发布/.test(bodyText));\n    return {\n      url: location.href,\n      title: document.title,\n      hasLogin,\n      fileInputCount: fileInputs.length,\n      fileInputs,\n      titleHints,\n      publishBtns,\n      progress,\n      editReady,\n      bodySnippet: bodyText.slice(0, 240),\n    };\n  })()";
}
function getFillTitleDescScript(arg1, arg2) {
  const result = JSON.stringify(String(arg1 || "").slice(0, 60));
  const result2 = JSON.stringify(String(arg2 || "").slice(0, 1000));
  return "(() => {\n    const titleText = " + result + ";\n    const descText = " + result2 + ";\n    function setNativeValue(el, value) {\n      const proto = el.tagName === 'TEXTAREA' ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype;\n      const setter = Object.getOwnPropertyDescriptor(proto, 'value')?.set;\n      if (setter) setter.call(el, value);\n      else el.value = value;\n      el.dispatchEvent(new Event('input', { bubbles: true }));\n      el.dispatchEvent(new Event('change', { bubbles: true }));\n    }\n    function fillEditable(el, value) {\n      el.focus();\n      if (el.isContentEditable) {\n        el.innerText = value;\n        el.dispatchEvent(new InputEvent('input', { bubbles: true, data: value }));\n        return true;\n      }\n      if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {\n        setNativeValue(el, value);\n        return true;\n      }\n      return false;\n    }\n    function scoreTitle(el) {\n      const ph = (el.getAttribute('placeholder') || '') + (el.getAttribute('aria-label') || '');\n      let s = 0;\n      if (/标题|作品标题|输入标题/.test(ph)) s += 5;\n      if (el.tagName === 'INPUT') s += 2;\n      if ((el.getAttribute('maxlength') || '') === '30' || (el.getAttribute('maxlength') || '') === '55') s += 1;\n      return s;\n    }\n    function scoreDesc(el) {\n      const ph = (el.getAttribute('placeholder') || '') + (el.getAttribute('aria-label') || '');\n      let s = 0;\n      if (/描述|作品描述|添加作品描述|简介/.test(ph)) s += 5;\n      if (el.isContentEditable) s += 2;\n      if (el.tagName === 'TEXTAREA') s += 2;\n      return s;\n    }\n    const candidates = Array.from(document.querySelectorAll('input, textarea, [contenteditable=\"true\"]'));\n    let titleEl = null;\n    let descEl = null;\n    let bestT = 0;\n    let bestD = 0;\n    for (const el of candidates) {\n      const st = scoreTitle(el);\n      if (st > bestT) { bestT = st; titleEl = el; }\n      const sd = scoreDesc(el);\n      if (sd > bestD) { bestD = sd; descEl = el; }\n    }\n    // 兜底：第一个 input 当标题，第一个 contenteditable/textarea 当描述\n    if (!titleEl || bestT < 2) {\n      titleEl = candidates.find((el) => el.tagName === 'INPUT' && !/search|搜索/.test(el.getAttribute('placeholder') || '')) || titleEl;\n    }\n    if (!descEl || bestD < 2) {\n      descEl = candidates.find((el) => el !== titleEl && (el.isContentEditable || el.tagName === 'TEXTAREA')) || descEl;\n    }\n    const titleOk = titleEl ? fillEditable(titleEl, titleText) : false;\n    const descOk = descEl && descText ? fillEditable(descEl, descText) : !descText;\n    return { titleOk, descOk, bestT, bestD };\n  })()";
}
function getClickPublishScript() {
  return "(() => {\n    const prefer = ['发布', '立即发布'];\n    const avoid = ['定时发布', '存草稿', '草稿'];\n    const nodes = Array.from(document.querySelectorAll('button, [role=\"button\"], .semi-button, div[class*=\"button\"]'));\n    const scored = [];\n    for (const el of nodes) {\n      const t = (el.innerText || el.textContent || '').trim().replace(/\\s+/g, '');\n      if (!t || t.length > 8) continue;\n      if (avoid.some((a) => t.includes(a))) continue;\n      let score = 0;\n      if (prefer.some((p) => t === p)) score += 10;\n      else if (prefer.some((p) => t.includes(p))) score += 5;\n      else continue;\n      const disabled = el.disabled || el.getAttribute('aria-disabled') === 'true' || /disabled|is-disabled/.test(el.className || '');\n      if (disabled) score -= 20;\n      scored.push({ el, t, score });\n    }\n    scored.sort((a, b) => b.score - a.score);\n    if (!scored.length || scored[0].score < 5) return { ok: false, reason: 'no_publish_button' };\n    try {\n      scored[0].el.click();\n      return { ok: true, text: scored[0].t };\n    } catch (e) {\n      return { ok: false, reason: e.message || 'click_failed' };\n    }\n  })()";
}
function getPublishResultScript() {
  return "(() => {\n    const text = (document.body && (document.body.innerText || '')) || '';\n    const url = location.href;\n    if (/发布成功|作品已发布|已发布成功|提交成功/.test(text)) return { ok: true, kind: 'success_text' };\n    if (/content\\/manage|content\\/published|作品管理|内容管理/.test(url) && /已发布|作品/.test(text)) {\n      return { ok: true, kind: 'manage_page' };\n    }\n    if (/上传失败|发布失败|网络异常|请重新上传|违规|审核/.test(text)) {\n      return { ok: false, kind: 'error_text', message: (text.match(/上传失败[^\\n]{0,40}|发布失败[^\\n]{0,40}|违规[^\\n]{0,40}/) || ['发布失败'])[0] };\n    }\n    return { ok: null, kind: 'pending' };\n  })()";
}
module.exports = {
  CREATOR_UPLOAD_URL: "https://creator.douyin.com/creator-micro/content/upload",
  getDismissDialogScript: getDismissDialogScript,
  getPageProbeScript: getPageProbeScript,
  getFillTitleDescScript: getFillTitleDescScript,
  getClickPublishScript: getClickPublishScript,
  getPublishResultScript: getPublishResultScript
};